### ISSUE TITLE
Using Videotagger for image files

### ISSUE THREAD

**Issue by ali-fairbrass** [groakat/videotagger#106]
Can Videotagger be used for image files or only videos?

**Comment by macaodha** [comment]
Just vids at the moment. What kind of image annotations do you need to do, because I might be able to point you to other tools.

**Comment by ali-fairbrass** [comment]
Thanks Oisin, not to worry that good to know.

**Comment by ali-fairbrass** [comment]
@macaodha Is there any way it could be used for image files? Kate is keen to use it to process some camera trap data.

**Comment by macaodha** [comment]
Check with @groakat, but I think there might be easier alternatives. 

There are some students in Caltech who have lots of experience in annotating camera trap images. I can put you in contact if you like. They are using [this](https://github.com/visipedia/annotation_tools) tool.
